name: Semgrep

on:
  pull_request: {}
  push:
    branches: ["master", "main"]
  schedule:
    - cron: '20 17 * * *'

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep

    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v3

      - name: Run Semgrep with JSON output
        run: semgrep ci --output results.json
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Upload JSON results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: semgrep-results
          path: results.json
